In [44]:
import numpy as np
import pandas as pd

In [45]:
dataset = pd.read_excel("DataSet.xlsx")
dataset.head(10)

   qd  gos  training2  creadit3  capital  gender  experience  age  education
0   0    0          1         1      1.5       0           8   45          5
1   0    0          1         0      0.3       0           1   29         12
2   0    0          0         0      9.0       1           5   35         18
3   1    0          1         0      9.5       1          12   56         10
4   0    0          0         0     13.0       1           8   50         32
5   0    1          0         1      5.0       0           8   47         16
6   0    0          0         0      2.0       1          12   58         16
7   0    0          1         1      0.3       0           3   34          8
8   0    0          0         0      4.0       0           5   51         12
9   0    0          0         1      1.5       1           3   35          0

In [46]:
print(len(dataset))
q_low = dataset["age"].quantile(0.05)
q_hi  = dataset["age"].quantile(0.95)
dataset = dataset[(dataset["age"] < q_hi) & (dataset["age"] > q_low)]
print(len(dataset))
print(dataset)

404
350
     qd  gos  training2  creadit3  capital  gender  experience  age  education
0     0    0          1         1      1.5       0           8   45          5
1     0    0          1         0      0.3       0           1   29         12
2     0    0          0         0      9.0       1           5   35         18
3     1    0          1         0      9.5       1          12   56         10
4     0    0          0         0     13.0       1           8   50         32
..   ..  ...        ...       ...      ...     ...         ...  ...        ...
398   0    0          1         0      1.0       0           3   31          5
399   0    0          0         0      1.0       1           4   40         20
400   0    0          1         0      3.0       1           6   32          9
401   0    1          0         0     10.0       1           2   35          0
402   0    0          0         1      7.0       1          11   56         18

[350 rows x 9 columns]

In [3]:
corr = dataset.corr()
corr.style.background_gradient(cmap='coolwarm')

In [4]:
# input
x = dataset.iloc[:, [1,2,3,4,5,6,7,8]].values

# output
y = dataset.iloc[:,0].values

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset[["gos","training2","creadit3","capital","gender","experience","age","education"]],dataset["qd"], test_size = 0.2)
TargetDataFrameTrain = pd.DataFrame(X_train,columns= ["GOS", "training2", "creadit3", "capital", "gender", "experience", "age", "education"])
TargetDataFrameTrain.insert(8, "qd", y_train, True)
TargetDataFrameTrain.insert(9, "INDEX", X_train.index.values, True)
# TargetDataFrameTrain.to_excel("RequestedTraindata.xlsx")

In [48]:
print(X_train.index.values)

[275  95 150 103  10 166 370  98 274 389 144 132 342   3 125  33   1 387
 124 361 240 213  29  30 130 220 319  93 113  35  58 359 255 304 402 139
   6 285  86 394 375 343   0 349 312 257  90  75 373  36  99 288 175 143
  14 372 266 197 172  54 297 271  83 251 268 318 263 232 114 214 401 137
 374  91 243 259 325  68 198  28  49 309 236  62 272 152  94 239 381 329
 287 382 209 339 376  13 315  73 192 320  34  97 369 135  12 126 179 313
 281 383 145 101 178 228 112  46 141  24  56  69 206 138  82 195 316 253
 344 180 296 234 371 116  53  37 284 276 393 357 164 367 146   2 326 336
 390 277 368 354 231  67 237 226 249 223 241 302 399 295 128 151  18 133
 294 260  89 391 301 118 341  96 317 388  17 360 244 203 250 378 305 184
 202 134 189 131  42  80  43 205  84 159 196 334 104 358 193  66  60  19
 262  79  39 396  40  21  61 347 308  11 173 216   5 188  76 264  59  26
  22 201 331   4 299 292  25 353 171  85 290  57 187  27 181  16 177 395
 362 346 398  88 384 298 364   9 167 286 340 337 127 147 352 365 247  74
  87  31   7 190 327 351  72 211 233 355 363 122 183  55 291 321  63 110
 273 140 246 212 256 278 100 230 169 108]

In [49]:
import statsmodels.api as sm
logit_model = sm.Logit(y_train,X_train)
result = logit_model.fit(disp=0)
#display(result.summary())

# ListCoef = [exec(f"x{i}ZValue = ") for i in range(1:9)]

while(True):
    X_train, X_test, y_train, y_test = train_test_split(dataset[["gos","training2","creadit3","capital","gender","experience","age","education"]],dataset["qd"], test_size = 0.2)
    logit_model = sm.Logit(y_train, X_train)
    result = logit_model.fit(disp=0, fit_intercept = True)
    
    x3ZValue = result.tvalues[2]
    x5ZValue = result.tvalues[4]

    x3Coef = result.params[2]
    x5Coef = result.params[4]
    if((abs(x3ZValue) > 1.96 and abs(x5ZValue) < 1.96 ) and (x3Coef > 0 and x5Coef >0)):
        display(result.summary())
        display(pd.DataFrame(X_train,columns= ["gos", "training2", "creadit3", "capital", "gender", "experience", "age", "education"]))
        break

E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                     qd   No. Observations:                  280
Model:                          Logit   Df Residuals:                      272
Method:                           MLE   Df Model:                            7
Date:                Thu, 01 Dec 2022   Pseudo R-squ.:                  0.1299
Time:                        02:30:40   Log-Likelihood:                -137.94
converged:                       True   LL-Null:                       -158.54
Covariance Type:            nonrobust   LLR p-value:                 7.402e-07
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
gos            1.5595      0.428      3.639      0.000       0.720       2.399
training2      0.9867      0.321      3.070      0.002       0.357       1.617
creadit3       0.6606      0.311      2.125      0.034       0.051       1.270
capital        0.0677      0.039      1.751      0.080      -0.008       0.144
gender         0.0848      0.293      0.289      0.772      -0.489       0.659
experience     0.2915      0.080      3.626      0.000       0.134       0.449
age           -0.1149      0.019     -5.977      0.000      -0.153      -0.077
education      0.0514      0.023      2.204      0.028       0.006       0.097
==============================================================================
"""

     gos  training2  creadit3  capital  gender  experience  age  education
219    0          0         1      9.0       0           2   33          8
101    0          0         0      2.0       0           1   37         16
246    0          1         0      1.0       0          12   57          8
220    0          1         0      7.5       1           8   46         18
349    1          1         0      8.0       1           9   54         13
..   ...        ...       ...      ...     ...         ...  ...        ...
103    0          0         1      9.0       1           3   34         20
62     0          0         1      7.0       0           8   54         12
292    0          0         0      2.0       0          11   49          8
239    1          0         0      1.0       1           8   45          5
337    0          1         0     12.0       0           7   54         16

[280 rows x 8 columns]

In [20]:
from sklearn.metrics import confusion_matrix
y_pred = result.predict(X_test)
y_pred = y_pred.apply(lambda x: 1 if x > 0.5 else 0)
qd = confusion_matrix(y_test, y_pred)
qd = pd.DataFrame(qd)
print("\nConfusion Matrix : \n", qd)

Confusion Matrix :
     0  1
0  59  1
1  18  3

In [24]:
def accuracy(pred_table):
    """
    Precision given pred_table. Binary classification only. Assumes group 0
    is the True.
    """
    tp, fp, fn, tn = map(float, pred_table.flatten())
    return (tp + tn) / (tp + tn + fp + fn)
accuracy(qd)

AttributeError: 'DataFrame' object has no attribute 'flatten'

In [58]:
for i in range(8):
    exec(f"x{i}ZValue = result.tvalues[{i}]")
for i in range(8):
    exec(f"x{i}Coef = result.params[{i}]")

In [117]:
def ConvertCondition(string):
    string = string.lower()
    string = string.replace("+",">")
    string = string.replace("yes",">")
    string = string.replace("no","<")
    string = string.replace("-","<")
    Condition = string.split(", ")
    return Condition

Check = 0
print(FinalCondition)
def CheckCondition():
    for i in range(0,8):
        stringC1 = FinalCondition[i][0]
        stringC2 = FinalCondition[i][1]
        Scondition = f"""
if(x{i}Coef {stringC1} 0 and x{i}ZValue {stringC2} 1.96):
    Check += 1
        """
        exec(Scondition, globals())
CheckCondition()
print(Check)
def change():
    global Check
    Check = "Hello"

change()
print(Check)

[['>', '>'], ['>', '>'], ['>', '>'], ['>', '<'], ['>', '<'], ['>', '>'], ['<', '<'], ['>', '<']]
8
Hello

In [112]:

FinalCondition = []
for i in range(1,9):
    exec(f"""
while(True):
    Condition = ConvertCondition(input("Input condition of x{i}:")) 
    if(len(Condition) < 2):
        Condition = ConvertCondition(input("Input condition of x{i}:")) 
    if(len(Condition) > 1):
        FinalCondition.append(Condition)
        break
    """)
    
        
print(FinalCondition)
Check = False
Scondition = f"""
if(x1Coef{Condition1[0]}0 ):
    Check = True
"""
exec(Scondition)
print(Check)

Input condition of x1: +, yes
Input condition of x2: +, yes
Input condition of x3: +, yes
Input condition of x4: +, no
Input condition of x5: +, no
Input condition of x6: +, yes
Input condition of x7: -, no
Input condition of x8: +, no

[['>', '>'], ['>', '>'], ['>', '>'], ['>', '<'], ['>', '<'], ['>', '>'], ['<', '<'], ['>', '<']]
False

In [50]:
import statsmodels.api as sm

#display(result.summary())

# ListCoef = [exec(f"x{i}ZValue = ") for i in range(1:9)]

X_train, X_test, y_train, y_test = train_test_split(dataset[["gos","training2","creadit3","capital","gender","experience","age","education"]],dataset["qd"], test_size = 0.05, random_state = 1)
logit_model = sm.Logit(y_train,sm.add_constant(X_train))
#logit_model = sm.Logit(y_train,X_train)
result = logit_model.fit(disp=0)

x3ZValue = result.tvalues[2]
x5ZValue = result.tvalues[4]

x3Coef = result.params[8]
x5Coef = result.params[4]
display(result.summary())
print(x3Coef)

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                     qd   No. Observations:                  332
Model:                          Logit   Df Residuals:                      323
Method:                           MLE   Df Model:                            8
Date:                Thu, 01 Dec 2022   Pseudo R-squ.:                  0.1113
Time:                        02:30:55   Log-Likelihood:                -167.84
converged:                       True   LL-Null:                       -188.86
Covariance Type:            nonrobust   LLR p-value:                 1.334e-06
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.1185      0.997     -2.124      0.034      -4.073      -0.164
gos            1.2566      0.383      3.279      0.001       0.505       2.008
training2      1.1230      0.318      3.534      0.000       0.500       1.746
creadit3       0.6073      0.295      2.057      0.040       0.029       1.186
capital        0.0768      0.036      2.145      0.032       0.007       0.147
gender         0.0631      0.270      0.233      0.815      -0.466       0.593
experience     0.2032      0.081      2.501      0.012       0.044       0.362
age           -0.0564      0.029     -1.958      0.050      -0.113    4.98e-05
education      0.0562      0.022      2.594      0.009       0.014       0.099
==============================================================================
"""

0.05620313188243005

In [52]:
for i in range(1,8):
    print(i)

1
2
3
4
5
6
7