In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_excel("DataSet.xlsx")
dataset.head(10)

   qd  gos  training2  creadit3  capital  gender  experience  age  education
0   0    0          1         1      1.5       0           8   45          5
1   0    0          1         0      0.3       0           1   29         12
2   0    0          0         0      9.0       1           5   35         18
3   1    0          1         0      9.5       1          12   56         10
4   0    0          0         0     13.0       1           8   50         32
5   0    1          0         1      5.0       0           8   47         16
6   0    0          0         0      2.0       1          12   58         16
7   0    0          1         1      0.3       0           3   34          8
8   0    0          0         0      4.0       0           5   51         12
9   0    0          0         1      1.5       1           3   35          0

In [25]:
print(len(dataset))
q_low = dataset["age"].quantile(0.05)
q_hi  = dataset["age"].quantile(0.95)
dataset = dataset[(dataset["age"] < q_hi) & (dataset["age"] > q_low)]
print(len(dataset))

404
350

In [3]:
corr = dataset.corr()
corr.style.background_gradient(cmap='coolwarm')

In [4]:
# input
x = dataset.iloc[:, [1,2,3,4,5,6,7,8]].values

# output
y = dataset.iloc[:,0].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset[["gos","training2","creadit3","capital","gender","experience","age","education"]],dataset["qd"], test_size = 0.2)
TargetDataFrameTrain = pd.DataFrame(X_train,columns= ["GOS", "training2", "creadit3", "capital", "gender", "experience", "age", "education"])
TargetDataFrameTrain.insert(8, "qd", y_train, True)
TargetDataFrameTrain.insert(9, "INDEX", X_train.index.values, True)
# TargetDataFrameTrain.to_excel("RequestedTraindata.xlsx")

In [6]:
print(X_train.index.values)

[170  67 196 306 394 381 137 250 251 372 225 104  16 117  97  90 344  42
  70 216 226 234 287  76 264  86 204 331 158 273 380 359 108 315 134  18
 309  98 150 274 121  20 208   5 180 189 210 348 260 335 116 357 374  75
  64 330 371 164 242  48 128 167 299 316  88  82 131 238 363 370 325 326
 122  24 384 132 154  34 115 100 387 347 144  22  93 368 275  74 334 118
 310  87 257 229 207 205 280 322 110  53 136 284 379 237  50 285 332 153
   6 366 103 339 232 178 252  81 212 301 176 243  41 148 338 247 105 392
 369   8 293 223 209 254 311  89 382  96 123  61 185 389  54  19 391 248
 261  15  83  58 220 125 361 236 320 186  69 107 215 168 127 290 174 239
  29 188 244 395 390 367 318 272  23 190 155 112 337 291 102 286 267 288
 341 192 302 246 305 307  37 201 181 294 298 202 175 308 240 126 271 265
 171 364 340 183 345 143 277 249 393 399 140 206 328   3  28 142  71 152
 295   0 214  32  26 217  59 266 342 263 106 303 203 396  85  21  44 222
 166 163 141 187  72 323  57 245  40 269  11  36  14 114 297 160 138 161
 403 173 193 386 235 346 101 213 378  65 327 270  62 219 321 111   4 400
 179 129 199 397  31  17  92  25  66  78 198  95  43 139  35 162  77 227
 146 130  47 313 352 156 241 300 197 200  39 281  52 383 230  99 336 191
 133  45  10 401 113 402 360   9 362 258 231 388 373 333 259  33   7]

In [8]:
import statsmodels.api as sm
logit_model = sm.Logit(y_train,X_train)
result = logit_model.fit(disp=0)
#display(result.summary())

# ListCoef = [exec(f"x{i}ZValue = ") for i in range(1:9)]

while(True):
    X_train, X_test, y_train, y_test = train_test_split(dataset[["gos","training2","creadit3","capital","gender","experience","age","education"]],dataset["qd"], test_size = 0.2)
    logit_model = sm.Logit(y_train, X_train)
    result = logit_model.fit(disp=0, fit_intercept = True)
    
    x3ZValue = result.tvalues[2]
    x5ZValue = result.tvalues[4]

    x3Coef = result.params[2]
    x5Coef = result.params[4]
    if((abs(x3ZValue) > 1.96 and abs(x5ZValue) < 1.96 ) and (x3Coef > 0 and x5Coef >0)):
        display(result.summary())
        display(pd.DataFrame(X_train,columns= ["gos", "training2", "creadit3", "capital", "gender", "experience", "age", "education"]))
        break

E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(
E:\anaconda3\envs\NLP\lib\site-packages\statsmodels\base\optimizer.py:17: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method newton is: tol. The list of unsupported keyword arguments passed include: fit_intercept. After release 0.14, this will raise.
  warnings.warn(

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                     qd   No. Observations:                  323
Model:                          Logit   Df Residuals:                      315
Method:                           MLE   Df Model:                            7
Date:                Thu, 01 Dec 2022   Pseudo R-squ.:                 0.07617
Time:                        01:45:42   Log-Likelihood:                -168.05
converged:                       True   LL-Null:                       -181.91
Covariance Type:            nonrobust   LLR p-value:                 0.0002478
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
gos            0.9664      0.383      2.521      0.012       0.215       1.718
training2      0.6585      0.285      2.310      0.021       0.100       1.217
creadit3       0.6132      0.286      2.141      0.032       0.052       1.174
capital        0.0491      0.036      1.373      0.170      -0.021       0.119
gender         0.0105      0.266      0.040      0.968      -0.510       0.531
experience     0.3012      0.068      4.414      0.000       0.167       0.435
age           -0.1027      0.017     -6.202      0.000      -0.135      -0.070
education      0.0455      0.022      2.087      0.037       0.003       0.088
==============================================================================
"""

     gos  training2  creadit3  capital  gender  experience  age  education
201    0          1         0      4.0       0           8   48         20
275    0          0         1      1.5       0           3   34          0
354    0          0         1      2.0       0           9   55         16
109    0          0         0      9.0       0          13   60         20
368    0          1         0      6.0       0          13   58          2
..   ...        ...       ...      ...     ...         ...  ...        ...
375    0          1         1      3.0       0           8   49         16
79     0          0         1     12.0       1           7   52          9
10     0          1         1      1.0       0           1   38          3
374    0          1         0      1.0       0           1   30          9
227    0          1         0      9.0       1           8   44          7

[323 rows x 8 columns]

In [20]:
from sklearn.metrics import confusion_matrix
y_pred = result.predict(X_test)
y_pred = y_pred.apply(lambda x: 1 if x > 0.5 else 0)
qd = confusion_matrix(y_test, y_pred)
qd = pd.DataFrame(qd)
print("\nConfusion Matrix : \n", qd)

Confusion Matrix :
     0  1
0  59  1
1  18  3

In [24]:
def accuracy(pred_table):
    """
    Precision given pred_table. Binary classification only. Assumes group 0
    is the True.
    """
    tp, fp, fn, tn = map(float, pred_table.flatten())
    return (tp + tn) / (tp + tn + fp + fn)
accuracy(qd)

AttributeError: 'DataFrame' object has no attribute 'flatten'

In [58]:
for i in range(8):
    exec(f"x{i}ZValue = result.tvalues[{i}]")
for i in range(8):
    exec(f"x{i}Coef = result.params[{i}]")

In [117]:
def ConvertCondition(string):
    string = string.lower()
    string = string.replace("+",">")
    string = string.replace("yes",">")
    string = string.replace("no","<")
    string = string.replace("-","<")
    Condition = string.split(", ")
    return Condition

Check = 0
print(FinalCondition)
def CheckCondition():
    for i in range(0,8):
        stringC1 = FinalCondition[i][0]
        stringC2 = FinalCondition[i][1]
        Scondition = f"""
if(x{i}Coef {stringC1} 0 and x{i}ZValue {stringC2} 1.96):
    Check += 1
        """
        exec(Scondition, globals())
CheckCondition()
print(Check)
def change():
    global Check
    Check = "Hello"

change()
print(Check)

[['>', '>'], ['>', '>'], ['>', '>'], ['>', '<'], ['>', '<'], ['>', '>'], ['<', '<'], ['>', '<']]
8
Hello

In [112]:

FinalCondition = []
for i in range(1,9):
    exec(f"""
while(True):
    Condition = ConvertCondition(input("Input condition of x{i}:")) 
    if(len(Condition) < 2):
        Condition = ConvertCondition(input("Input condition of x{i}:")) 
    if(len(Condition) > 1):
        FinalCondition.append(Condition)
        break
    """)
    
        
print(FinalCondition)
Check = False
Scondition = f"""
if(x1Coef{Condition1[0]}0 ):
    Check = True
"""
exec(Scondition)
print(Check)

Input condition of x1: +, yes
Input condition of x2: +, yes
Input condition of x3: +, yes
Input condition of x4: +, no
Input condition of x5: +, no
Input condition of x6: +, yes
Input condition of x7: -, no
Input condition of x8: +, no

[['>', '>'], ['>', '>'], ['>', '>'], ['>', '<'], ['>', '<'], ['>', '>'], ['<', '<'], ['>', '<']]
False

In [29]:
import statsmodels.api as sm

#display(result.summary())

# ListCoef = [exec(f"x{i}ZValue = ") for i in range(1:9)]

X_train, X_test, y_train, y_test = train_test_split(dataset[["gos","training2","creadit3","capital","gender","experience","age","education"]],dataset["qd"], test_size = 0.2, random_state = 1)
logit_model = sm.Logit(y_train,sm.add_constant(X_train))
#logit_model = sm.Logit(y_train,X_train)
result = logit_model.fit(disp=0)

x3ZValue = result.tvalues[2]
x5ZValue = result.tvalues[4]

x3Coef = result.params[0]
x5Coef = result.params[4]
display(result.summary())
print(x3Coef)

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                     qd   No. Observations:                  323
Model:                          Logit   Df Residuals:                      314
Method:                           MLE   Df Model:                            8
Date:                Sat, 26 Nov 2022   Pseudo R-squ.:                 0.08459
Time:                        02:06:44   Log-Likelihood:                -167.52
converged:                       True   LL-Null:                       -182.99
Covariance Type:            nonrobust   LLR p-value:                 0.0001429
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.5130      0.907     -2.772      0.006      -4.290      -0.736
gos            1.0416      0.392      2.658      0.008       0.273       1.810
training2      1.0119      0.312      3.246      0.001       0.401       1.623
creadit3       0.4405      0.299      1.474      0.140      -0.145       1.026
capital        0.0375      0.037      1.018      0.309      -0.035       0.110
gender        -0.0215      0.270     -0.080      0.936      -0.551       0.508
experience     0.1514      0.075      2.015      0.044       0.004       0.299
age           -0.0274      0.026     -1.046      0.295      -0.079       0.024
education      0.0484      0.022      2.171      0.030       0.005       0.092
==============================================================================
"""

-2.51304116192178